language: cpp
compiler:
  - clang
os: osx
osx_image: xcode10.1
dist: trusty
addons:
  homebrew:
    packages:
      - cmake
      - gsl
      - boost
      - libomp
script:
  - git clone https://github.com/junseonghwan/spf.git
  - pwd
  - ls
  - mkdir spf/build
  - cd spf/build
  - cmake ..
  - make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
